name: EmeraldWarp
main: ElementalMinecraftGaming\EmeraldWarp\Main
version: 1.0.0
api: [3.5.5]
load: POSTWORLD
author: ElementalMinecraftGaming
description: Set warps and use them!

commands:
 emeraldsetwarp:
  description: Set a warp!
  usage: "/emeraldsetwarp {warp}"
  permission: emerald.setwarp
  aliases: [esw]
 emeraldwarp:
  description: Warp!
  usage: "/emeraldwarp {warp}"
  permission: emerald.warp
  aliases: [ew]
 emeraldlistwarps:
  description: List Warps!
  usage: "/emeraldlistwarps"
  permission: emerald.listw
  aliases: [elw]
 emeraldelwarp:
  description: delete Warps!
  usage: "/emeraldelwarp"
  permission: emerald.delwarp
  aliases: [edw]

permissions:
  emerald.setwarp:
    default: op
    description: Let's you use /esw {warp}
  emerald.warp:
    default: true
    description: Let's you use /ew {warp}
  emerald.listw:
    default: true
    description: Let's you use /elw
  emerald.delwarp:
    default: op
    description: Let's you use /edw
